services:
  mysql:
    container_name: mysql_container
    hostname: mysql
    domainname: fqdn.com
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3906:3306"
    networks:
        my-data-environment:
            ipv4_address: 172.20.0.3
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--bind-address=0.0.0.0',
      '--mysql-native-password=ON',
      '--skip-log-bin'
    ]      
    restart: unless-stopped
  
networks: 
    my-data-environment: 
        external: true
volumes:
  db_data: